- name: Git Clone prezto
  git: repo=https://github.com/sorin-ionescu/prezto.git
       dest={{ ansible_env.HOME }}/.zprezto
       update=no

- name: Symlink add configuration prezto zlogin
  file: src={{ ansible_env.HOME }}/.zprezto/runcoms/zlogin dest={{ ansible_env.HOME }}/.zlogin state=link

- name: Symlink add configuration prezto zlogout
  file: src={{ ansible_env.HOME }}/.zprezto/runcoms/zlogout dest={{ ansible_env.HOME }}/.zlogout state=link

- name: Symlink add configuration prezto zprofile
  file: src={{ ansible_env.HOME }}/.zprezto/runcoms/zprofile dest={{ ansible_env.HOME }}/.zprofile state=link

- name: Template present prezto configuration .zpreztorc
  template: src=zpreztorc.j2 dest={{ ansible_env.HOME }}/.zpreztorc

- name: Template present prezto initialize file .zshrc
  template: src=prezto.init.sh.j2 dest={{ ansible_env.HOME }}/.zsh/prezto.init.sh

- name: Add .zshrc prezto.init.sh
  lineinfile:
    dest={{ ansible_env.HOME }}/.zshrc
    line="source ~/.zsh/prezto.init.sh"
    insertbefore=BOF state=present regexp="prezto\.init\.sh"
  notify:
    - execute source .zshrc
