- name: Check oh-my-zsh installed
  stat: path=~/.oh-my-zsh
  register: installed

- name: Install oh-my-zsh
  shell: curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh
  when: installed.stat.exists == false
