- name: Install the readline in the brew.
  homebrew: name=readline state=present
  when: "ansible_os_family == 'Darwin'"

- name: Install readline from yum
  yum: pkg=readline-devel state=present
  when: "ansible_os_family == 'RedHat'"
