- name: Install the wget in the brew.
  homebrew: name=wget state=present
  when: "ansible_os_family == 'Darwin'"

- name: Install wget from yum
  yum: pkg=wget state=present
  when: "ansible_os_family == 'RedHat'"
