- name: Check using shell register in file path
  shell: |
      if [ `echo $SHELL | grep -c "zsh"` -eq 1 ]; then
        echo "~/.zshrc"
      elif [ `echo $SHELL | grep -c "bash"` -eq 1 ]; then
        if [ `uname` = "Linux" ]; then
          echo "~/.bashrc"
        elif [ `uname` = "Darwin" ]; then
          echo "~/.bash_profile"
        fi
      fi
  # 書き込むログインshell fileを保存しておきたいだけなので常にokの状態に保つ
  # see http://qiita.com/ryurock/items/639e5f7e49d25c3b6d75
  changed_when: False
  register: shell_dotfile

- name: Check using shell register in dir
  shell: |
      if [ `echo $SHELL | grep -c "zsh"` -eq 1 ]; then
        echo "~/.zsh"
      elif [ `echo $SHELL | grep -c "bash"` -eq 1 ]; then
        echo "~/.bash"
      fi
  changed_when: False
  register: shell_dotfile_dir

- name: Create directory shell_dotfile name
  action:
    file path={{ shell_dotfile_dir.stdout }} state=directory mode=0755

- name: Template present common.sh
  action:
    template src=common.sh.j2 dest={{ shell_dotfile_dir.stdout }}/common.sh
 
- name: Check shell_dotfile source common.sh
  action:
    shell cat {{ shell_dotfile.stdout }} | grep -c 'source {{ shell_dotfile_dir.stdout }}/common.sh'
  failed_when: no
  changed_when: False
  register: command_result

- name: Add shell_dotfile source common.sh
  action: 
    lineinfile dest={{shell_dotfile.stdout}} line='source {{ shell_dotfile_dir.stdout }}/common.sh'
  when: command_result.stdout == "0"
  notify:
    - execute source shell_dotfile
