- name: Check homebrew installed
  stat: path=/usr/local/bin/brew
  register: installed

- name: Install homebrew
  shell: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  when: installed.stat.exists == false
